
name: Build Win1223

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish EXE
        shell: pwsh
        run: |
          dotnet publish src/Win1223.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            /p:PublishSingleFile=true `
            /p:PublishTrimmed=false

      - uses: actions/upload-artifact@v4
        with:
          name: Win1223
          path: src/bin/Release/net8.0-windows/win-x64/publish/Win1223.exe
