<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>WinExe</OutputType>

    <TargetFramework>net8.0-windows</TargetFramework>

    <UseWindowsForms>true</UseWindowsForms>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <SelfContained>true</SelfContained>

    <PublishSingleFile>true</PublishSingleFile>

    <!-- 真正有效的瘦身 -->
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>

    <PublishReadyToRun>false</PublishReadyToRun>

    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <DebugType>none</DebugType>

    <InvariantGlobalization>true</InvariantGlobalization>

    <AssemblyName>Win1223</AssemblyName>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>

  </PropertyGroup>

</Project>
