<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- Native AOT -->
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>

    <!-- NativeAOT不能和PublishSingleFile同时开启 -->
    <InvariantGlobalization>true</InvariantGlobalization>

    <AssemblyName>Win1223</AssemblyName>
    <Product>Win1223 Cloud PC</Product>
    <Company>1223.fun</Company>

    <FileVersion>4.0.0.0</FileVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>

    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
