name: Build Win1223

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Publish
        shell: pwsh
        run: |
          dotnet publish src/Win1223.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: Win1223
          path: src/bin/Release/net8.0-windows/win-x64/publish/Win1223.exe
